// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftstays/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetMarketRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetMarketRequest) Reset()         { *m = QueryGetMarketRequest{} }
func (m *QueryGetMarketRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMarketRequest) ProtoMessage()    {}
func (*QueryGetMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{0}
}
func (m *QueryGetMarketRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMarketRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMarketRequest.Merge(m, src)
}
func (m *QueryGetMarketRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMarketRequest proto.InternalMessageInfo

func (m *QueryGetMarketRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetMarketResponse struct {
	Market *Market `protobuf:"bytes,1,opt,name=Market,proto3" json:"Market,omitempty"`
}

func (m *QueryGetMarketResponse) Reset()         { *m = QueryGetMarketResponse{} }
func (m *QueryGetMarketResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMarketResponse) ProtoMessage()    {}
func (*QueryGetMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{1}
}
func (m *QueryGetMarketResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMarketResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMarketResponse.Merge(m, src)
}
func (m *QueryGetMarketResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMarketResponse proto.InternalMessageInfo

func (m *QueryGetMarketResponse) GetMarket() *Market {
	if m != nil {
		return m.Market
	}
	return nil
}

type QueryAllMarketRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMarketRequest) Reset()         { *m = QueryAllMarketRequest{} }
func (m *QueryAllMarketRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMarketRequest) ProtoMessage()    {}
func (*QueryAllMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{2}
}
func (m *QueryAllMarketRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMarketRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMarketRequest.Merge(m, src)
}
func (m *QueryAllMarketRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMarketRequest proto.InternalMessageInfo

func (m *QueryAllMarketRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMarketResponse struct {
	Market     []*Market           `protobuf:"bytes,1,rep,name=Market,proto3" json:"Market,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMarketResponse) Reset()         { *m = QueryAllMarketResponse{} }
func (m *QueryAllMarketResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMarketResponse) ProtoMessage()    {}
func (*QueryAllMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{3}
}
func (m *QueryAllMarketResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMarketResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMarketResponse.Merge(m, src)
}
func (m *QueryAllMarketResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMarketResponse proto.InternalMessageInfo

func (m *QueryAllMarketResponse) GetMarket() []*Market {
	if m != nil {
		return m.Market
	}
	return nil
}

func (m *QueryAllMarketResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetNftStayRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetNftStayRequest) Reset()         { *m = QueryGetNftStayRequest{} }
func (m *QueryGetNftStayRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNftStayRequest) ProtoMessage()    {}
func (*QueryGetNftStayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{4}
}
func (m *QueryGetNftStayRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNftStayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNftStayRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNftStayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNftStayRequest.Merge(m, src)
}
func (m *QueryGetNftStayRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNftStayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNftStayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNftStayRequest proto.InternalMessageInfo

func (m *QueryGetNftStayRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetNftStayResponse struct {
	NftStay *NftStay `protobuf:"bytes,1,opt,name=NftStay,proto3" json:"NftStay,omitempty"`
}

func (m *QueryGetNftStayResponse) Reset()         { *m = QueryGetNftStayResponse{} }
func (m *QueryGetNftStayResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNftStayResponse) ProtoMessage()    {}
func (*QueryGetNftStayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{5}
}
func (m *QueryGetNftStayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNftStayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNftStayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNftStayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNftStayResponse.Merge(m, src)
}
func (m *QueryGetNftStayResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNftStayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNftStayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNftStayResponse proto.InternalMessageInfo

func (m *QueryGetNftStayResponse) GetNftStay() *NftStay {
	if m != nil {
		return m.NftStay
	}
	return nil
}

type QueryAllNftStayRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNftStayRequest) Reset()         { *m = QueryAllNftStayRequest{} }
func (m *QueryAllNftStayRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNftStayRequest) ProtoMessage()    {}
func (*QueryAllNftStayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{6}
}
func (m *QueryAllNftStayRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNftStayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNftStayRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNftStayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNftStayRequest.Merge(m, src)
}
func (m *QueryAllNftStayRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNftStayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNftStayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNftStayRequest proto.InternalMessageInfo

func (m *QueryAllNftStayRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllNftStayResponse struct {
	NftStay    []*NftStay          `protobuf:"bytes,1,rep,name=NftStay,proto3" json:"NftStay,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNftStayResponse) Reset()         { *m = QueryAllNftStayResponse{} }
func (m *QueryAllNftStayResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNftStayResponse) ProtoMessage()    {}
func (*QueryAllNftStayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_823be6c882eb8edf, []int{7}
}
func (m *QueryAllNftStayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNftStayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNftStayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNftStayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNftStayResponse.Merge(m, src)
}
func (m *QueryAllNftStayResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNftStayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNftStayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNftStayResponse proto.InternalMessageInfo

func (m *QueryAllNftStayResponse) GetNftStay() []*NftStay {
	if m != nil {
		return m.NftStay
	}
	return nil
}

func (m *QueryAllNftStayResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetMarketRequest)(nil), "kryptopoo.marketplace.nftstays.QueryGetMarketRequest")
	proto.RegisterType((*QueryGetMarketResponse)(nil), "kryptopoo.marketplace.nftstays.QueryGetMarketResponse")
	proto.RegisterType((*QueryAllMarketRequest)(nil), "kryptopoo.marketplace.nftstays.QueryAllMarketRequest")
	proto.RegisterType((*QueryAllMarketResponse)(nil), "kryptopoo.marketplace.nftstays.QueryAllMarketResponse")
	proto.RegisterType((*QueryGetNftStayRequest)(nil), "kryptopoo.marketplace.nftstays.QueryGetNftStayRequest")
	proto.RegisterType((*QueryGetNftStayResponse)(nil), "kryptopoo.marketplace.nftstays.QueryGetNftStayResponse")
	proto.RegisterType((*QueryAllNftStayRequest)(nil), "kryptopoo.marketplace.nftstays.QueryAllNftStayRequest")
	proto.RegisterType((*QueryAllNftStayResponse)(nil), "kryptopoo.marketplace.nftstays.QueryAllNftStayResponse")
}

func init() { proto.RegisterFile("nftstays/query.proto", fileDescriptor_823be6c882eb8edf) }

var fileDescriptor_823be6c882eb8edf = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x6a, 0x53, 0x41,
	0x14, 0xc7, 0x33, 0xa9, 0xad, 0x38, 0x82, 0x8b, 0xc1, 0x56, 0x09, 0x72, 0x91, 0x59, 0x34, 0xf1,
	0x6b, 0x86, 0xb4, 0x7e, 0xec, 0x84, 0xb8, 0xb0, 0x0b, 0x51, 0x34, 0x6e, 0x44, 0x04, 0x9d, 0x24,
	0xd3, 0xeb, 0xa5, 0x37, 0x77, 0xa6, 0x99, 0x89, 0x18, 0xc4, 0x8d, 0x4f, 0x20, 0xf8, 0x04, 0x2e,
	0xdc, 0x88, 0x88, 0x6f, 0xa1, 0xcb, 0x82, 0x1b, 0x97, 0x92, 0xf8, 0x20, 0x92, 0x99, 0x93, 0x9b,
	0xcf, 0xf6, 0xde, 0x94, 0x6e, 0x87, 0xf3, 0xff, 0x9f, 0xdf, 0xf9, 0x9f, 0x7b, 0x12, 0x7c, 0x3e,
	0xd9, 0xb5, 0xc6, 0x8a, 0x9e, 0xe1, 0xfb, 0x5d, 0xd9, 0xe9, 0x31, 0xdd, 0x51, 0x56, 0x91, 0x60,
	0xaf, 0xd3, 0xd3, 0x56, 0x69, 0xa5, 0x58, 0x5b, 0x74, 0xf6, 0xa4, 0xd5, 0xb1, 0x68, 0x4a, 0x36,
	0xaa, 0x2d, 0x5d, 0x0a, 0x95, 0x0a, 0x63, 0xc9, 0x85, 0x8e, 0xb8, 0x48, 0x12, 0x65, 0x85, 0x8d,
	0x54, 0x62, 0xbc, 0xba, 0x74, 0xb5, 0xa9, 0x4c, 0x5b, 0x19, 0xde, 0x10, 0x46, 0x7a, 0x5b, 0xfe,
	0xa6, 0xda, 0x90, 0x56, 0x54, 0xb9, 0x16, 0x61, 0x94, 0xb8, 0x62, 0xa8, 0x5d, 0x4f, 0xfb, 0xfb,
	0x46, 0xf0, 0xbc, 0x91, 0x3e, 0x27, 0xbb, 0xf6, 0xa9, 0x15, 0x00, 0x46, 0xcb, 0x78, 0xfd, 0xc9,
	0xd0, 0x70, 0x47, 0xda, 0x87, 0xae, 0xbe, 0x2e, 0xf7, 0xbb, 0xd2, 0x58, 0x72, 0x0e, 0x17, 0xa3,
	0xd6, 0x45, 0x74, 0x19, 0x55, 0x4e, 0xd5, 0x8b, 0x51, 0x8b, 0x3e, 0xc3, 0x1b, 0xb3, 0x85, 0x46,
	0xab, 0xc4, 0x48, 0x72, 0x17, 0xaf, 0xf9, 0x17, 0x57, 0x7d, 0x76, 0x6b, 0x93, 0x1d, 0x3d, 0x2c,
	0x03, 0x3d, 0xa8, 0xe8, 0x4b, 0x40, 0xa8, 0xc5, 0xf1, 0x34, 0xc2, 0x7d, 0x8c, 0xc7, 0xe3, 0xa5,
	0xe6, 0x3e, 0x0b, 0x36, 0xcc, 0x82, 0xf9, 0x88, 0x21, 0x0b, 0xf6, 0x58, 0x84, 0x12, 0xb4, 0xf5,
	0x09, 0x25, 0xfd, 0x8c, 0x80, 0x7d, 0xa2, 0xc3, 0x02, 0xf6, 0x95, 0xe5, 0xd9, 0xc9, 0xce, 0x14,
	0x62, 0xd1, 0x21, 0x96, 0x33, 0x11, 0x7d, 0xf3, 0x29, 0xc6, 0xca, 0x38, 0xde, 0x47, 0x7e, 0x41,
	0x87, 0x2d, 0xe2, 0x05, 0xbe, 0x30, 0x57, 0x09, 0xd3, 0xd4, 0xf0, 0x69, 0x78, 0x82, 0xb4, 0xca,
	0x59, 0xe3, 0x8c, 0x1c, 0x46, 0x3a, 0xfa, 0x6a, 0x1c, 0xd5, 0x0c, 0xc7, 0x49, 0x6d, 0xe3, 0x0b,
	0x82, 0x01, 0x26, 0x5b, 0x2c, 0x1a, 0x60, 0xe5, 0x38, 0x03, 0x9c, 0xd8, 0x46, 0xb6, 0x7e, 0xae,
	0xe2, 0x55, 0xc7, 0x49, 0xbe, 0xa1, 0xd1, 0x57, 0x42, 0x6e, 0x65, 0xf1, 0x2c, 0x3c, 0xa6, 0xd2,
	0xed, 0x65, 0x65, 0x9e, 0x87, 0x6e, 0x7f, 0xf8, 0xfd, 0xef, 0x53, 0xf1, 0x06, 0xb9, 0xc6, 0x53,
	0x3d, 0x9f, 0xd0, 0xf3, 0x99, 0x5b, 0xe7, 0xef, 0xa2, 0xd6, 0x7b, 0xf2, 0x15, 0xe1, 0x33, 0xde,
	0xa7, 0x16, 0xc7, 0x39, 0x89, 0x67, 0x6f, 0x2f, 0x27, 0xf1, 0xdc, 0x41, 0x51, 0xe6, 0x88, 0x2b,
	0x64, 0x33, 0x1f, 0x31, 0xf9, 0x81, 0xd2, 0x95, 0x93, 0xdc, 0x29, 0x4d, 0x7f, 0x99, 0xa5, 0x3b,
	0x4b, 0xeb, 0x00, 0xf6, 0xa6, 0x83, 0x65, 0xe4, 0x7a, 0x16, 0x2c, 0xfc, 0x66, 0xfa, 0x7c, 0xbf,
	0x23, 0x8c, 0xc1, 0x69, 0x18, 0x70, 0xee, 0xa4, 0x8e, 0x45, 0x3d, 0x7f, 0x24, 0x94, 0x3b, 0xea,
	0x2b, 0xa4, 0x9c, 0x93, 0xfa, 0xde, 0x83, 0x5f, 0xfd, 0x00, 0x1d, 0xf4, 0x03, 0xf4, 0xb7, 0x1f,
	0xa0, 0x8f, 0x83, 0xa0, 0x70, 0x30, 0x08, 0x0a, 0x7f, 0x06, 0x41, 0xe1, 0x79, 0x35, 0x8c, 0xec,
	0xeb, 0x6e, 0x83, 0x35, 0x55, 0xfb, 0x10, 0xb3, 0xb7, 0x63, 0x3b, 0xdb, 0xd3, 0xd2, 0x34, 0xd6,
	0xdc, 0xff, 0xc6, 0xf6, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xab, 0x2f, 0x73, 0xe8, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a market by id.
	Market(ctx context.Context, in *QueryGetMarketRequest, opts ...grpc.CallOption) (*QueryGetMarketResponse, error)
	// Queries a list of market items.
	MarketAll(ctx context.Context, in *QueryAllMarketRequest, opts ...grpc.CallOption) (*QueryAllMarketResponse, error)
	// Queries a nftStay by id.
	NftStay(ctx context.Context, in *QueryGetNftStayRequest, opts ...grpc.CallOption) (*QueryGetNftStayResponse, error)
	// Queries a list of nftStay items.
	NftStayAll(ctx context.Context, in *QueryAllNftStayRequest, opts ...grpc.CallOption) (*QueryAllNftStayResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Market(ctx context.Context, in *QueryGetMarketRequest, opts ...grpc.CallOption) (*QueryGetMarketResponse, error) {
	out := new(QueryGetMarketResponse)
	err := c.cc.Invoke(ctx, "/kryptopoo.marketplace.nftstays.Query/Market", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MarketAll(ctx context.Context, in *QueryAllMarketRequest, opts ...grpc.CallOption) (*QueryAllMarketResponse, error) {
	out := new(QueryAllMarketResponse)
	err := c.cc.Invoke(ctx, "/kryptopoo.marketplace.nftstays.Query/MarketAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NftStay(ctx context.Context, in *QueryGetNftStayRequest, opts ...grpc.CallOption) (*QueryGetNftStayResponse, error) {
	out := new(QueryGetNftStayResponse)
	err := c.cc.Invoke(ctx, "/kryptopoo.marketplace.nftstays.Query/NftStay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NftStayAll(ctx context.Context, in *QueryAllNftStayRequest, opts ...grpc.CallOption) (*QueryAllNftStayResponse, error) {
	out := new(QueryAllNftStayResponse)
	err := c.cc.Invoke(ctx, "/kryptopoo.marketplace.nftstays.Query/NftStayAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a market by id.
	Market(context.Context, *QueryGetMarketRequest) (*QueryGetMarketResponse, error)
	// Queries a list of market items.
	MarketAll(context.Context, *QueryAllMarketRequest) (*QueryAllMarketResponse, error)
	// Queries a nftStay by id.
	NftStay(context.Context, *QueryGetNftStayRequest) (*QueryGetNftStayResponse, error)
	// Queries a list of nftStay items.
	NftStayAll(context.Context, *QueryAllNftStayRequest) (*QueryAllNftStayResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Market(ctx context.Context, req *QueryGetMarketRequest) (*QueryGetMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Market not implemented")
}
func (*UnimplementedQueryServer) MarketAll(ctx context.Context, req *QueryAllMarketRequest) (*QueryAllMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketAll not implemented")
}
func (*UnimplementedQueryServer) NftStay(ctx context.Context, req *QueryGetNftStayRequest) (*QueryGetNftStayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftStay not implemented")
}
func (*UnimplementedQueryServer) NftStayAll(ctx context.Context, req *QueryAllNftStayRequest) (*QueryAllNftStayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftStayAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Market_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Market(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kryptopoo.marketplace.nftstays.Query/Market",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Market(ctx, req.(*QueryGetMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MarketAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MarketAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kryptopoo.marketplace.nftstays.Query/MarketAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MarketAll(ctx, req.(*QueryAllMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NftStay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNftStayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NftStay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kryptopoo.marketplace.nftstays.Query/NftStay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NftStay(ctx, req.(*QueryGetNftStayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NftStayAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNftStayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NftStayAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kryptopoo.marketplace.nftstays.Query/NftStayAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NftStayAll(ctx, req.(*QueryAllNftStayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kryptopoo.marketplace.nftstays.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Market",
			Handler:    _Query_Market_Handler,
		},
		{
			MethodName: "MarketAll",
			Handler:    _Query_MarketAll_Handler,
		},
		{
			MethodName: "NftStay",
			Handler:    _Query_NftStay_Handler,
		},
		{
			MethodName: "NftStayAll",
			Handler:    _Query_NftStayAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nftstays/query.proto",
}

func (m *QueryGetMarketRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMarketRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMarketRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMarketResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMarketResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMarketResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Market != nil {
		{
			size, err := m.Market.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMarketRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMarketRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMarketRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMarketResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMarketResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMarketResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Market) > 0 {
		for iNdEx := len(m.Market) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Market[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNftStayRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNftStayRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNftStayRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNftStayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNftStayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNftStayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NftStay != nil {
		{
			size, err := m.NftStay.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNftStayRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNftStayRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNftStayRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNftStayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNftStayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNftStayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NftStay) > 0 {
		for iNdEx := len(m.NftStay) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftStay[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetMarketRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetMarketResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Market != nil {
		l = m.Market.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMarketRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMarketResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Market) > 0 {
		for _, e := range m.Market {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNftStayRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetNftStayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NftStay != nil {
		l = m.NftStay.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNftStayRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNftStayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NftStay) > 0 {
		for _, e := range m.NftStay {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetMarketRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMarketRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMarketRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMarketResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMarketResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMarketResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Market", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Market == nil {
				m.Market = &Market{}
			}
			if err := m.Market.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMarketRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMarketRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMarketRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMarketResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMarketResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMarketResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Market", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Market = append(m.Market, &Market{})
			if err := m.Market[len(m.Market)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNftStayRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNftStayRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNftStayRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNftStayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNftStayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNftStayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftStay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NftStay == nil {
				m.NftStay = &NftStay{}
			}
			if err := m.NftStay.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNftStayRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNftStayRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNftStayRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNftStayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNftStayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNftStayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftStay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftStay = append(m.NftStay, &NftStay{})
			if err := m.NftStay[len(m.NftStay)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
